### ISSUE TITLE
Remove hardcoded PORT in tests

### ISSUE THREAD

**Issue by ritch** [strongloop/strong-mesh-client#21]
Use the following instead:

``` js
var net = require('net');
var portrange = 9000;

module.exports = function getPort(cb) {
  var port = portrange;
  portrange += 1;

  var server = net.createServer();
  server.listen(port, function (err) {
    server.once('close', function () {
      cb(port);
    });
    server.close();
  });
  server.on('error', function (err) {
    getPort(cb);
  });
}
```

**Comment by rmg** [comment]
That `getPort` implementation is extremely racy.. If a client connects before the socket is fully closes it won't close properly. If another script is running on the same server using the same code they could easily get the same port and cause all sorts of weird cross-talk behaviour..

Why not use IPC?

**Comment by rmg** [comment]
This is probably not going to happen, so I'm closing.
