### ISSUE TITLE
Unable to generate browser bundle (osx 10.11.1 / npm: 3.4.0 / node: 5.1.0)

### ISSUE THREAD

**Issue by OpethiaN73** [strongloop/strong-mesh-client#44]
Getting this error on: npm install strongloop -g --no-optional 

unable to generate browser bundle: Cannot find module 'jodid25519' from '/Users/OpethiaN/.node/lib/node_modules/strongloop/node_modules/sshpk/lib'
npm WARN install:strong-mesh-client@1.6.3 strong-mesh-client@1.6.3 install: `node proxy/build-client.js`
npm WARN install:strong-mesh-client@1.6.3 Exit status 1

> spawn-sync@1.0.14 postinstall /Users/OpethiaN/.node/lib/node_modules/strongloop/node_modules/spawn-sync
> node postinstall

/Users/OpethiaN/.node/lib
└── (empty)

npm WARN EPEERINVALID loopback@2.25.0 requires a peer of loopback-datasource-juggler@^2.19.0 but none was installed.
npm ERR! code 1
[OpethiaN@OpieOSX node_modules ]$ npm -v
3.4.0
[OpethiaN@OpieOSX node_modules ]$ node -v
v5.1.0

**Comment by rmg** [comment]
This issue is quite old and would be unrelated to the changes in #58 and `strong-mesh-client@1.6.5`, but everything _appears_ to be working as of those versions.

@OpethiaN73 please re-open if you are still having this problem.
