### ISSUE TITLE
Failed at the strong-mesh-client@1.6.3 install script 'node proxy/build-client.js'.

### ISSUE THREAD

**Issue by jorgeramos** [strongloop/strong-mesh-client#45]
got the following error when running npm install -g strongloop 
 i also have issues deploying new build of my strongloop app to heroku

```
npm ERR! strong-mesh-client@1.6.3 install: `node proxy/build-client.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the strong-mesh-client@1.6.3 install script 'node proxy/build-client.js'.
npm ERR! This is most likely a problem with the strong-mesh-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node proxy/build-client.js
```

**Comment by jorgeramos** [comment]
seems like this was a phantom issue... the update worked fine after the 4th attempt

**Comment by Abode113** [comment]
I think that (loopback) version is old version you need to install the newest version (loopback-cli)
so you need to type on terminal :
$ sudo npm install -g loopback-cli
