### ISSUE TITLE
install script fails because not all deps are installed yet

### ISSUE THREAD

**Issue by bajtos** [strongloop/strong-mesh-client#50]
We are observing CI failures in this repository when running downstream/dependent jobs. See https://cis-jenkins.swg-devops.com/job/ds/job/strong-arc~master/152/console

```
> strong-mesh-client@1.6.3 install /home/jenkins/workspace/ds/strong-arc~master/node_modules/strong-mesh-client
> node proxy/build-client.js

module.js:327
    throw err;
    ^

Error: Cannot find module 'lodash/_MapCache'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/jenkins/workspace/ds/strong-arc~master/node_modules/loopback-boot/node_modules/strong-globalize/lib/globalize.js:14:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

This is caused by the fact that the `install` script is loading dependent modules. This is not reliable, because npm does not guarantee that all dependencies are already installed at the time an `install` script is run. (Related: https://github.com/npm/npm/issues/6926)

@rmg @sam-github what are our options here? 

I can add `loopback-boot` to `bundledDependencies`, but I am afraid that will only delay the problem until we load other files, most notably `strong-mesh-models` (see [here](https://github.com/strongloop/strong-mesh-client/blob/32819c656c210ebd102e7b95d40a5090e3d0170d/proxy/build-client.js#L86-L98)). If we add `strong-mesh-models` to `bundledDependencies`, then I think that will defeat the purpose of re-building the client in a (post)install hook.

For npm@3 (Node@6), moving the script to `postinstall` hook should solve the problem (thanks to https://github.com/npm/npm/issues/6926).

How to fix it for Node v0.10-v4.x?

cc @strongloop/loopback-dev

**Comment by rmg** [comment]
I agree this is a problem. We've been lucky so far that it hasn't caused more trouble than it has.

@kraman I recall there was a reason for doing this as an `install` instead of `prepublish`.. something about ensuring that the latest loopback was used or something along those lines. Is that still a concern?

**Comment by sam-github** [comment]
Same question as Ryan's, why isn't this a prepublish? Install scripts cannot reliably write to disk, so doing anything other than console.log in an install script is not robust.

@rmg when doing a in-package install, as CI does, prepublish gets run IIRC. Will prepublish get run only when all deps are completely installed? If not, then vendoring the required deps in might be the only solution, but that won't work, right, because the purpose is to not have a hard dep on a particular mesh models version?

Perhaps mesh models can be generating a browserified client for itself in a prepublish, so that mesh client doesn't have to? Would that fix this?

/cc @kraman @ritch

**Comment by kraman** [comment]
In apim-ui, this is a pre-publish script. We should do the same for Arc.
Is Arc still being supported? I thought we were going to stop distributing it.
@sumitha ?

**Comment by ritch** [comment]
Closing for now... please re-open if this is important enough to keep on our backlog.

**Comment by sam-github** [comment]
@ritch it causes downstream failures in at least strong-arc, I'm OK not fixing, but the actual problem, that unrelated code is failing in CI because it fails here, is a problem in getting CI green. Maybe this can just be marked as not a relevant down-stream, somehow?

**Comment by dvnrsn** [comment]
Update: ran in cmd rather than git bash, seems to avoid problem.

```
> strong-mesh-client@1.6.5 install C:\Users\\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-arc\node_modules\strong-mesh-client
> node proxy/build-client.js

module.js:471
    throw err;
    ^

Error: Cannot find module './_MapCache'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\\AppData\Roaming\npm\node_modules\strongloop\node_modules\strong-arc\node_modules\loopback-boot\node_modules\strong-globalize\node_modules\lodash\memoize.js:1:78)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
npm ERR! Windows_NT 10.0.16299
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "strongloop"
npm ERR! node v6.11.3
npm ERR! npm  v2.15.12
npm ERR! code ELIFECYCLE
```

I'm having this issue in trying to npm install -g strongloop. What can I do?

**Comment by bajtos** [comment]
@dvnrsn I am not sure what's the official status of support for `strongloop` package, our [FAQ](https://strongloop.com/faq/) is advising users to upgrade to [IBM API Connect](https://developer.ibm.com/apiconnect/getting-started/):

> Arc has been replaced by API Connect. No one new can register for (or use) Arc. Only previously-registered users can use Arc and get support.
>
> We recommend Arc users move to the Essentials edition of API Connect. If you have questions, please email reachsl@us.ibm.com.

If you the Essentials edition of API Connect does not suit your needs, then please drop an email to reachsl@us.ibm.com to get more help.
