### ISSUE TITLE
installation fails

### ISSUE THREAD

**Issue by pallavibhakare** [strongloop/strong-mesh-client#54]
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: modern-syslog@^1.1.2 (node_modul
es\strongloop\node_modules\modern-syslog):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for modern-sy
slog@1.1.4: wanted {"os":"!win32","arch":"any"} (current: {"os":"win32","arch":"
x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: modern-syslog@^1.x (node_modules
\strongloop\node_modules\strong-supervisor\node_modules\modern-syslog):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for modern-sy
slog@1.1.4: wanted {"os":"!win32","arch":"any"} (current: {"os":"win32","arch":"
x64"})
npm ERR! Windows_NT 6.3.9600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Pallavi\\AppData
\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "strongloop"
npm ERR! node v6.9.4
npm ERR! npm  v4.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! strong-mesh-client@1.6.3 install: `node proxy/build-client.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the strong-mesh-client@1.6.3 install script 'node proxy/build
-client.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the strong-mesh-client pa
ckage,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node proxy/build-client.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs strong-mesh-client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls strong-mesh-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Pallavi\AppData\Roaming\npm-cache\_logs\2017-03-06T21_33_3
2_004Z-debug.log

=== from the log =====
186192 warn optional SKIPPING OPTIONAL DEPENDENCY: modern-syslog@^1.1.2 (node_modules\strongloop\node_modules\modern-syslog):
186193 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for modern-syslog@1.1.4: wanted {"os":"!win32","arch":"any"} (current: {"os":"win32","arch":"x64"})
186194 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    !win32
186194 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
186194 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
186194 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
186195 warn optional SKIPPING OPTIONAL DEPENDENCY: modern-syslog@^1.x (node_modules\strongloop\node_modules\strong-supervisor\node_modules\modern-syslog):
186196 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for modern-syslog@1.1.4: wanted {"os":"!win32","arch":"any"} (current: {"os":"win32","arch":"x64"})
186197 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    !win32
186197 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
186197 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   win32
186197 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
186198 verbose stack Error: strong-mesh-client@1.6.3 install: `node proxy/build-client.js`
186198 verbose stack Exit status 1
186198 verbose stack     at EventEmitter.<anonymous> (C:\Users\Pallavi\AppData\Roaming\npm\node_modules\npm\lib\utils\lifecycle.js:279:16)
186198 verbose stack     at emitTwo (events.js:106:13)
186198 verbose stack     at EventEmitter.emit (events.js:191:7)
186198 verbose stack     at ChildProcess.<anonymous> (C:\Users\Pallavi\AppData\Roaming\npm\node_modules\npm\lib\utils\spawn.js:40:14)
186198 verbose stack     at emitTwo (events.js:106:13)
186198 verbose stack     at ChildProcess.emit (events.js:191:7)
186198 verbose stack     at maybeClose (internal/child_process.js:877:16)
186198 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
186199 verbose pkgid strong-mesh-client@1.6.3
186200 verbose cwd C:\windows\system32
186201 error Windows_NT 6.3.9600
186202 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Pallavi\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "strongloop"
186203 error node v6.9.4
186204 error npm  v4.3.0
186205 error code ELIFECYCLE
186206 error errno 1
186207 error strong-mesh-client@1.6.3 install: `node proxy/build-client.js`
186207 error Exit status 1
186208 error Failed at the strong-mesh-client@1.6.3 install script 'node proxy/build-client.js'.
186208 error Make sure you have the latest version of node.js and npm installed.
186208 error If you do, this is most likely a problem with the strong-mesh-client package,
186208 error not with npm itself.
186208 error Tell the author that this fails on your system:
186208 error     node proxy/build-client.js
186208 error You can get information on how to open an issue for this project with:
186208 error     npm bugs strong-mesh-client
186208 error Or if that isn't available, you can get their info via:
186208 error     npm owner ls strong-mesh-client
186208 error There is likely additional logging output above.
186209 verbose exit [ 1, true ]

**Comment by rmg** [comment]
There isn't any detail in the error message other than `node proxy/build-client.js` failed. I strongly suspect this is actually the same as #53 so I'm going to close this one to avoid confusion.

**Comment by pallavibhakare** [comment]
thank you for the reply.  yes, it is same as #53.  It got solved by uninstalling the previous node and again by installing node.
