### ISSUE TITLE
CI fails in master and 1.x branch

### ISSUE THREAD

**Issue by dhmlau** [strongloop/strong-mesh-client#60]
CI fails in master and 1.x branch causing `loopback-datasource-juggler` for 2.x branch CI fails. 

Both CI failed with the same error: 
```
java.lang.NullPointerException
ERROR: Step ‘Archive the artifacts’ failed: no workspace for ds/strong-mesh-client~1.x #332
```

Full logs can be found here: 
https://cis-jenkins.swg-devops.com/job/ds/job/strong-mesh-client~1.x/332/console
https://cis-jenkins.swg-devops.com/job/ds/job/strong-mesh-client~master/332/console

**Related issue**: https://github.com/strongloop/loopback-datasource-juggler/pull/1342

**Comment by rmg** [comment]
These particular failures are unrelated to the referenced issue and were due to infrastructure problems which have been resolved.
